
import { Faction, Hero, PuzzleType, PuzzleDefinition, HeroClass } from './types';

export const HERO_DATABASE: Hero[] = [
  { id: 1, name: '매튜궁병', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY], classes: [HeroClass.ARCHER, HeroClass.INFANTRY] },
  { id: 2, name: '매튜기병', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY], classes: [HeroClass.CAVALRY, HeroClass.INFANTRY] },
  { id: 3, name: '매튜비병', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY], classes: [HeroClass.FLYER, HeroClass.INFANTRY] },
  { id: 4, name: '매튜암살자', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY], classes: [HeroClass.ASSASSIN, HeroClass.INFANTRY] },
  { id: 5, name: '아멜다', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 6, name: '그레니어', factions: [Faction.LEGION_OF_GLORY], classes: [HeroClass.ARCHER, HeroClass.LANCER] },
  { id: 7, name: '아론', factions: [Faction.LEGION_OF_GLORY], classes: [HeroClass.LANCER] },
  { id: 8, name: '안나', factions: [Faction.EMPIRE_HONOR, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.HOLY] },
  { id: 9, name: '디오스', factions: [Faction.ORIGINS_OF_LIGHT, Faction.STRATEGIC_MASTERS], classes: [HeroClass.ARCHER] },
  { id: 10, name: '키스', factions: [Faction.LEGION_OF_GLORY], classes: [HeroClass.FLYER] },
  { id: 11, name: '제시카', factions: [Faction.LEGION_OF_GLORY, Faction.ORIGINS_OF_LIGHT, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE] },
  { id: 12, name: '스코트', factions: [Faction.LEGION_OF_GLORY, Faction.STRATEGIC_MASTERS], classes: [HeroClass.CAVALRY] },
  { id: 13, name: '로우가', factions: [Faction.EMPIRE_HONOR, Faction.METEOR_STRIKE], classes: [HeroClass.ASSASSIN] },
  { id: 14, name: '루인', factions: [Faction.ORIGINS_OF_LIGHT], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 15, name: '레아드', factions: [Faction.EMPIRE_HONOR, Faction.METEOR_STRIKE], classes: [HeroClass.CAVALRY] },
  { id: 16, name: '피엘', factions: [Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE], classes: [HeroClass.AQUATIC] },
  { id: 17, name: '레티시아', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS], classes: [HeroClass.CAVALRY] },
  { id: 18, name: '레스터', factions: [Faction.LEGION_OF_GLORY, Faction.METEOR_STRIKE], classes: [HeroClass.AQUATIC] },
  { id: 19, name: '소피아', factions: [Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE, Faction.TRANSCENDENCE], classes: [HeroClass.HOLY] },
  { id: 20, name: '페라키아', factions: [Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE], classes: [HeroClass.DEMON, HeroClass.ASSASSIN] },
  { id: 21, name: '프레아', factions: [Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.HOLY, HeroClass.LANCER] },
  { id: 22, name: '발가스', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 23, name: '파나', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION], classes: [HeroClass.ARCHER, HeroClass.FLYER] },
  { id: 24, name: '나암', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.METEOR_STRIKE], classes: [HeroClass.ARCHER, HeroClass.FLYER] },
  { id: 25, name: '크리스', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.HOLY] },
  { id: 26, name: '키리카제', factions: [Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.ASSASSIN] },
  { id: 27, name: '실버울프', factions: [Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 28, name: '소니아', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.CAVALRY, HeroClass.MAGE] },
  { id: 29, name: '에마링크', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS], classes: [HeroClass.CAVALRY, HeroClass.LANCER] },
  { id: 30, name: '이멜다', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 31, name: '리파니', factions: [Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.MAGE] },
  { id: 32, name: '에그베르트', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION, Faction.STRATEGIC_MASTERS], classes: [HeroClass.MAGE] },
  { id: 33, name: '헤인', factions: [Faction.LEGION_OF_GLORY, Faction.EMPIRE_HONOR], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 34, name: '란스', factions: [Faction.LEGION_OF_GLORY, Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS], classes: [HeroClass.CAVALRY, HeroClass.FLYER] },
  { id: 35, name: '보젤', factions: [Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 36, name: '레딘', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY], classes: [HeroClass.INFANTRY, HeroClass.HOLY] },
  { id: 37, name: '레온', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS], classes: [HeroClass.CAVALRY] },
  { id: 38, name: '베른하르트', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE], classes: [HeroClass.INFANTRY, HeroClass.DRAGON] },
  { id: 39, name: '라나', factions: [Faction.DARK_REINCARNATION, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 40, name: '엘윈', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.EMPIRE_HONOR], classes: [HeroClass.CAVALRY, HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 41, name: '쉐리', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.METEOR_STRIKE], classes: [HeroClass.FLYER, HeroClass.HOLY, HeroClass.ASSASSIN] },
  { id: 42, name: '리아나', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 43, name: '알테뮬러', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION, Faction.STRATEGIC_MASTERS], classes: [HeroClass.FLYER, HeroClass.LANCER] },
  { id: 44, name: '루나', factions: [Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE, Faction.STRATEGIC_MASTERS], classes: [HeroClass.ARCHER, HeroClass.FLYER] },
  { id: 45, name: '디하르트', factions: [Faction.PROTAGONIST, Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE], classes: [HeroClass.CAVALRY, HeroClass.ASSASSIN] },
  { id: 46, name: '티아리스', factions: [Faction.PROTAGONIST, Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 47, name: '쥬그라', factions: [Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE, Faction.TRANSCENDENCE], classes: [HeroClass.CAVALRY, HeroClass.AQUATIC, HeroClass.DRAGON] },
  { id: 48, name: '젤다', factions: [Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.ASSASSIN] },
  { id: 49, name: '제리올', factions: [Faction.ORIGINS_OF_LIGHT, Faction.STRATEGIC_MASTERS], classes: [HeroClass.CAVALRY, HeroClass.HOLY] },
  { id: 50, name: '셀파닐', factions: [Faction.PRINCESS_ALLIANCE, Faction.YELESS_LEGENDS], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 51, name: '안젤리나', factions: [Faction.PRINCESS_ALLIANCE, Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS], classes: [HeroClass.FLYER, HeroClass.AQUATIC] },
  { id: 52, name: '란포드', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS], classes: [HeroClass.CAVALRY, HeroClass.INFANTRY, HeroClass.FLYER] },
  { id: 53, name: '리스틸', factions: [Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS], classes: [HeroClass.DEMON] },
  { id: 54, name: '에스텔', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.TIME_AND_SPACE], classes: [HeroClass.LANCER] },
  { id: 55, name: '요슈아', factions: [Faction.PRINCESS_ALLIANCE, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.DEMON, HeroClass.ASSASSIN] },
  { id: 56, name: '클로제', factions: [Faction.PRINCESS_ALLIANCE, Faction.YELESS_LEGENDS, Faction.TIME_AND_SPACE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 57, name: '레온하르트', factions: [Faction.EMPIRE_HONOR, Faction.ORIGINS_OF_LIGHT, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 58, name: '렌', factions: [Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS, Faction.TIME_AND_SPACE], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 59, name: '올리비에', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.ARCHER] },
  { id: 60, name: '란디우스', factions: [Faction.PROTAGONIST, Faction.YELESS_LEGENDS], classes: [HeroClass.CAVALRY, HeroClass.LANCER] },
  { id: 61, name: '레이첼', factions: [Faction.PROTAGONIST, Faction.YELESS_LEGENDS], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 62, name: '윌러', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS], classes: [HeroClass.HOLY] },
  { id: 63, name: '기자로프', factions: [Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 64, name: '세레나', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 65, name: '시그마', factions: [Faction.PROTAGONIST, Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.ARCHER, HeroClass.INFANTRY, HeroClass.ASSASSIN] },
  { id: 66, name: '람다', factions: [Faction.PROTAGONIST, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 67, name: '사쿠라', factions: [Faction.PROTAGONIST, Faction.EMPIRE_HONOR, Faction.TIME_AND_SPACE], classes: [HeroClass.CAVALRY, HeroClass.INFANTRY] },
  { id: 68, name: '스미레', factions: [Faction.EMPIRE_HONOR, Faction.PRINCESS_ALLIANCE, Faction.TIME_AND_SPACE], classes: [HeroClass.CAVALRY, HeroClass.LANCER] },
  { id: 69, name: '아이리스', factions: [Faction.EMPIRE_HONOR, Faction.PRINCESS_ALLIANCE, Faction.TIME_AND_SPACE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 70, name: '안젤리카', factions: [Faction.LEGION_OF_GLORY, Faction.TIME_AND_SPACE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 71, name: '클라렛', factions: [Faction.PRINCESS_ALLIANCE, Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.FLYER] },
  { id: 72, name: '엘라스타', factions: [Faction.LEGION_OF_GLORY, Faction.ORIGINS_OF_LIGHT, Faction.STRATEGIC_MASTERS], classes: [HeroClass.ARCHER] },
  { id: 73, name: '오메가', factions: [Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 74, name: '유리아', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.TRANSCENDENCE], classes: [HeroClass.INFANTRY, HeroClass.HOLY] },
  { id: 75, name: '유스케', factions: [Faction.PROTAGONIST, Faction.TIME_AND_SPACE, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.HOLY] },
  { id: 76, name: '쿠라마', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS, Faction.TIME_AND_SPACE], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 77, name: '카즈마', factions: [Faction.LEGION_OF_GLORY, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 78, name: '히에이', factions: [Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.DEMON, HeroClass.ASSASSIN] },
  { id: 79, name: '도구로', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION, Faction.TIME_AND_SPACE], classes: [HeroClass.CAVALRY, HeroClass.DEMON] },
  { id: 80, name: '레인폴스', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.INFANTRY, HeroClass.ASSASSIN] },
  { id: 81, name: '베티', factions: [Faction.LEGION_OF_GLORY, Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION], classes: [HeroClass.INFANTRY] },
  { id: 82, name: '알프레드', factions: [Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.AQUATIC] },
  { id: 83, name: '환생제시카', factions: [Faction.LEGION_OF_GLORY, Faction.ORIGINS_OF_LIGHT, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 84, name: '에밀리아', factions: [Faction.EMPIRE_HONOR, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.HOLY, HeroClass.LANCER] },
  { id: 85, name: '비라쥬', factions: [Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.AQUATIC] },
  { id: 86, name: '미지의기사', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS], classes: [HeroClass.CAVALRY, HeroClass.MAGE] },
  { id: 87, name: '아카야', factions: [Faction.LEGION_OF_GLORY, Faction.ORIGINS_OF_LIGHT, Faction.TRANSCENDENCE], classes: [HeroClass.CAVALRY, HeroClass.MAGE] },
  { id: 88, name: '브렌다', factions: [Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.CAVALRY, HeroClass.LANCER] },
  { id: 89, name: '올리버', factions: [Faction.LEGION_OF_GLORY, Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.ASSASSIN] },
  { id: 90, name: '디드리트', factions: [Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE, Faction.TIME_AND_SPACE], classes: [HeroClass.MAGE, HeroClass.INFANTRY] },
  { id: 91, name: '아슈람', factions: [Faction.DARK_REINCARNATION, Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.CAVALRY, HeroClass.FLYER] },
  { id: 92, name: '판', factions: [Faction.PROTAGONIST, Faction.ORIGINS_OF_LIGHT, Faction.TIME_AND_SPACE], classes: [HeroClass.CAVALRY, HeroClass.INFANTRY] },
  { id: 93, name: '필로테스', factions: [Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 94, name: '아레스', factions: [Faction.PROTAGONIST, Faction.EMPIRE_HONOR, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.INFANTRY, HeroClass.FLYER] },
  { id: 95, name: '마이야', factions: [Faction.EMPIRE_HONOR, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 96, name: '일루시아', factions: [Faction.LEGION_OF_GLORY, Faction.STRATEGIC_MASTERS], classes: [HeroClass.AQUATIC, HeroClass.LANCER] },
  { id: 97, name: '실린카', factions: [Faction.METEOR_STRIKE, Faction.TRANSCENDENCE], classes: [HeroClass.ARCHER, HeroClass.INFANTRY] },
  { id: 98, name: '리코리스', factions: [Faction.DARK_REINCARNATION, Faction.PRINCESS_ALLIANCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.DEMON, HeroClass.HOLY] },
  { id: 99, name: '레나타', factions: [Faction.DARK_REINCARNATION, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.DRAGON, HeroClass.LANCER] },
  { id: 100, name: '린', factions: [Faction.PROTAGONIST, Faction.TRANSCENDENCE, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 101, name: '아리안로드', factions: [Faction.RE_INCARNATION_TENSEI, Faction.TRANSCENDENCE, Faction.TIME_AND_SPACE], classes: [HeroClass.HOLY, HeroClass.LANCER] },
  { id: 102, name: '알티나', factions: [Faction.EMPIRE_HONOR, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.MAGE, HeroClass.FLYER] },
  { id: 103, name: '로자리아', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.CAVALRY, HeroClass.HOLY] },
  { id: 104, name: '노에미', factions: [Faction.LEGION_OF_GLORY, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.MAGE] },
  { id: 105, name: '헬레나', factions: [Faction.LEGION_OF_GLORY, Faction.EMPIRE_HONOR], classes: [HeroClass.CAVALRY] },
  { id: 106, name: '세계수의현자', factions: [Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 107, name: '플로렌티아', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 108, name: '츠바메', factions: [Faction.RE_INCARNATION_TENSEI, Faction.METEOR_STRIKE], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 109, name: '아인즈', factions: [Faction.DARK_REINCARNATION, Faction.TIME_AND_SPACE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 110, name: '알베도', factions: [Faction.DARK_REINCARNATION, Faction.TIME_AND_SPACE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.DEMON, HeroClass.INFANTRY] },
  { id: 111, name: '샤르티아', factions: [Faction.DARK_REINCARNATION, Faction.TIME_AND_SPACE, Faction.METEOR_STRIKE], classes: [HeroClass.DEMON, HeroClass.LANCER] },
  { id: 112, name: '멜파니', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.YELESS_LEGENDS], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 113, name: '로젠실', factions: [Faction.EMPIRE_HONOR, Faction.TRANSCENDENCE, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 114, name: '클로테르', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS], classes: [HeroClass.MAGE, HeroClass.INFANTRY] },
  { id: 115, name: '탄생의빛', factions: [Faction.LEGION_OF_GLORY, Faction.ORIGINS_OF_LIGHT, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 116, name: '마리엘', factions: [Faction.LEGION_OF_GLORY, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.HOLY] },
  { id: 117, name: '힐다', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.CAVALRY, HeroClass.LANCER] },
  { id: 118, name: '베르너', factions: [Faction.EMPIRE_HONOR, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.CAVALRY] },
  { id: 119, name: '와타루', factions: [Faction.PROTAGONIST, Faction.YELESS_LEGENDS, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 120, name: '히미코', factions: [Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS, Faction.TIME_AND_SPACE], classes: [HeroClass.ASSASSIN] },
  { id: 121, name: '시바라쿠', factions: [Faction.YELESS_LEGENDS, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 122, name: '크루거', factions: [Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 123, name: '빈센트', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE], classes: [HeroClass.DEMON, HeroClass.FLYER] },
  { id: 124, name: '토와', factions: [Faction.RE_INCARNATION_TENSEI, Faction.ORIGINS_OF_LIGHT, Faction.STRATEGIC_MASTERS], classes: [HeroClass.INFANTRY, HeroClass.FLYER] },
  { id: 125, name: '팟시르', factions: [Faction.RE_INCARNATION_TENSEI, Faction.DARK_REINCARNATION], classes: [HeroClass.DEMON, HeroClass.ASSASSIN] },
  { id: 126, name: '크림조의왕', factions: [Faction.ORIGINS_OF_LIGHT, Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE], classes: [HeroClass.INFANTRY, HeroClass.HOLY] },
  { id: 127, name: '화이트시시', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 128, name: '료', factions: [Faction.PROTAGONIST, Faction.YELESS_LEGENDS, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY, HeroClass.HOLY] },
  { id: 129, name: '카유라', factions: [Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE, Faction.TIME_AND_SPACE], classes: [HeroClass.HOLY, HeroClass.ASSASSIN] },
  { id: 130, name: '토마', factions: [Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.ARCHER, HeroClass.HOLY] },
  { id: 131, name: '오토크라토4세', factions: [Faction.EMPIRE_HONOR, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.INFANTRY] },
  { id: 132, name: '루크레치아', factions: [Faction.EMPIRE_HONOR, Faction.PRINCESS_ALLIANCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 133, name: '입실론', factions: [Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.DEMON, HeroClass.INFANTRY] },
  { id: 134, name: '뮤', factions: [Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 135, name: '크리스티아네', factions: [Faction.EMPIRE_HONOR, Faction.PRINCESS_ALLIANCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.CAVALRY, HeroClass.INFANTRY] },
  { id: 136, name: '수제트', factions: [Faction.METEOR_STRIKE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 137, name: '초월자', factions: [Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.HOLY] },
  { id: 138, name: '알파', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 139, name: '베르너폰에길', factions: [Faction.LEGION_OF_GLORY, Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.ASSASSIN] },
  { id: 140, name: '마리안델', factions: [Faction.PRINCESS_ALLIANCE, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 141, name: '웨탐', factions: [Faction.PROTAGONIST, Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.FLYER] },
  { id: 142, name: '엘마', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.HOLY] },
  { id: 143, name: '켈티스', factions: [Faction.DARK_REINCARNATION, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 144, name: '로비나대제', factions: [Faction.PROTAGONIST, Faction.STRATEGIC_MASTERS, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.CAVALRY, HeroClass.INFANTRY] },
  { id: 145, name: '방주의성녀', factions: [Faction.PROTAGONIST, Faction.PRINCESS_ALLIANCE, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 146, name: '구스타프', factions: [Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 147, name: '미셸', factions: [Faction.LEGION_OF_GLORY, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 148, name: '리자', factions: [Faction.PROTAGONIST, Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 149, name: '아이언챈슬러', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS], classes: [HeroClass.INFANTRY, HeroClass.HOLY] },
  { id: 150, name: '크림조의집정관', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.AQUATIC] },
  { id: 151, name: '셀베리아', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.ARCHER, HeroClass.INFANTRY] },
  { id: 152, name: '알리시아', factions: [Faction.PROTAGONIST, Faction.TRANSCENDENCE, Faction.TIME_AND_SPACE], classes: [HeroClass.ARCHER] },
  { id: 153, name: '이사라', factions: [Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.ARCHER, HeroClass.CAVALRY] },
  { id: 154, name: '아즈사', factions: [Faction.ORIGINS_OF_LIGHT, Faction.STRATEGIC_MASTERS, Faction.TRANSCENDENCE], classes: [HeroClass.HOLY] },
  { id: 155, name: '오보로', factions: [Faction.ORIGINS_OF_LIGHT, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.DRAGON, HeroClass.LANCER] },
  { id: 156, name: '카구야', factions: [Faction.PRINCESS_ALLIANCE, Faction.STRATEGIC_MASTERS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 157, name: '캐롤리안', factions: [Faction.LEGION_OF_GLORY, Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS], classes: [HeroClass.CAVALRY] },
  { id: 158, name: '아샤메르', factions: [Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 159, name: '로스탐', factions: [Faction.ORIGINS_OF_LIGHT, Faction.STRATEGIC_MASTERS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.ASSASSIN] },
  { id: 160, name: '방랑투사', factions: [Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS], classes: [HeroClass.FLYER, HeroClass.LANCER] },
  { id: 161, name: '줄리안', factions: [Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 162, name: '리키', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.YELESS_LEGENDS], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 163, name: '마크렌', factions: [Faction.STRATEGIC_MASTERS, Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS], classes: [HeroClass.AQUATIC, HeroClass.ASSASSIN] },
  { id: 164, name: '긴토키', factions: [Faction.PROTAGONIST, Faction.TIME_AND_SPACE, Faction.YELESS_LEGENDS], classes: [HeroClass.INFANTRY] },
  { id: 165, name: '카구라', factions: [Faction.PROTAGONIST, Faction.PRINCESS_ALLIANCE, Faction.TIME_AND_SPACE], classes: [HeroClass.CAVALRY, HeroClass.LANCER] },
  { id: 166, name: '신파치', factions: [Faction.PROTAGONIST, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY, HeroClass.HOLY] },
  { id: 167, name: '아단켈모', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 168, name: '빛의수호사도', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.TRANSCENDENCE], classes: [HeroClass.INFANTRY, HeroClass.HOLY] },
  { id: 169, name: '빛과그림자검의영혼', factions: [Faction.PROTAGONIST, Faction.TRANSCENDENCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.DEMON, HeroClass.INFANTRY] },
  { id: 170, name: '껍질소녀', factions: [Faction.DARK_REINCARNATION, Faction.PRINCESS_ALLIANCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.MAGE] },
  { id: 171, name: '리오벡', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 172, name: '시엔', factions: [Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE, Faction.STRATEGIC_MASTERS], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 173, name: '폴리알', factions: [Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.HOLY, HeroClass.LANCER] },
  { id: 174, name: '루그너', factions: [Faction.LEGION_OF_GLORY, Faction.STRATEGIC_MASTERS, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 175, name: '그렌실', factions: [Faction.PRINCESS_ALLIANCE, Faction.STRATEGIC_MASTERS, Faction.ORIGINS_OF_LIGHT], classes: [HeroClass.INFANTRY, HeroClass.FLYER] },
  { id: 176, name: '요아&코니', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.ARCHER] },
  { id: 177, name: '아니에스', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.TIME_AND_SPACE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 178, name: '일레인', factions: [Faction.STRATEGIC_MASTERS, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 179, name: '반', factions: [Faction.PROTAGONIST, Faction.YELESS_LEGENDS, Faction.TIME_AND_SPACE], classes: [HeroClass.DEMON, HeroClass.INFANTRY] },
  { id: 180, name: '각성자', factions: [Faction.DARK_REINCARNATION, Faction.TIME_AND_SPACE, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 181, name: '사그니', factions: [Faction.YELESS_LEGENDS, Faction.STRATEGIC_MASTERS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 182, name: '아마데우스', factions: [Faction.ORIGINS_OF_LIGHT, Faction.STRATEGIC_MASTERS, Faction.TRANSCENDENCE], classes: [HeroClass.CAVALRY] },
  { id: 183, name: '키리카', factions: [Faction.YELESS_LEGENDS, Faction.PRINCESS_ALLIANCE, Faction.TIME_AND_SPACE], classes: [HeroClass.ARCHER] },
  { id: 184, name: '소니아블랑쉬', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 185, name: '엑셀러', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.FLYER, HeroClass.LANCER] },
  { id: 186, name: '님프', factions: [Faction.PRINCESS_ALLIANCE, Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.AQUATIC] },
  { id: 187, name: '타탈리아', factions: [Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE, Faction.TRANSCENDENCE], classes: [HeroClass.ASSASSIN] },
  { id: 188, name: '투어밀크', factions: [Faction.ORIGINS_OF_LIGHT, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 189, name: '이리스', factions: [Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.CAVALRY, HeroClass.HOLY] },
  { id: 190, name: '롤랑', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.YELESS_LEGENDS], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 191, name: '프레시아', factions: [Faction.PROTAGONIST, Faction.PRINCESS_ALLIANCE, Faction.TRANSCENDENCE], classes: [HeroClass.HOLY, HeroClass.LANCER] },
  { id: 192, name: '리나', factions: [Faction.PROTAGONIST, Faction.DARK_REINCARNATION, Faction.TIME_AND_SPACE], classes: [HeroClass.MAGE, HeroClass.INFANTRY] },
  { id: 193, name: '제르디가스', factions: [Faction.STRATEGIC_MASTERS, Faction.TRANSCENDENCE, Faction.TIME_AND_SPACE], classes: [HeroClass.MAGE, HeroClass.INFANTRY] },
  { id: 194, name: '가우리', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 195, name: '강신자', factions: [Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.FLYER] },
  { id: 196, name: '캡틴잭', factions: [Faction.LEGION_OF_GLORY, Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS], classes: [HeroClass.INFANTRY, HeroClass.AQUATIC] },
  { id: 197, name: '안드리올', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.METEOR_STRIKE], classes: [HeroClass.CAVALRY] },
  { id: 198, name: '네미아', factions: [Faction.LEGION_OF_GLORY, Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS], classes: [HeroClass.ARCHER] },
  { id: 199, name: '애쉬엔', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.FLYER] },
  { id: 200, name: '호프만', factions: [Faction.LEGION_OF_GLORY, Faction.STRATEGIC_MASTERS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 201, name: '이졸데', factions: [Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE, Faction.TRANSCENDENCE], classes: [HeroClass.INFANTRY, HeroClass.DRAGON] },
  { id: 202, name: '제이스', factions: [Faction.ORIGINS_OF_LIGHT, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 203, name: '페트리샤', factions: [Faction.EMPIRE_HONOR, Faction.PRINCESS_ALLIANCE, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE] },
  { id: 204, name: '군', factions: [Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS, Faction.METEOR_STRIKE], classes: [HeroClass.DEMON, HeroClass.INFANTRY] },
  { id: 205, name: '쇼우', factions: [Faction.PROTAGONIST, Faction.TRANSCENDENCE, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 206, name: '알칸펠', factions: [Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE, Faction.TIME_AND_SPACE], classes: [HeroClass.DEMON] },
  { id: 207, name: '아기토', factions: [Faction.YELESS_LEGENDS, Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 208, name: '빙설심연의지배자', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.CAVALRY, HeroClass.FLYER] },
  { id: 209, name: '타브리스', factions: [Faction.PRINCESS_ALLIANCE, Faction.STRATEGIC_MASTERS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.FLYER] },
  { id: 210, name: '테란틸', factions: [Faction.EMPIRE_HONOR, Faction.TRANSCENDENCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.INFANTRY, HeroClass.FLYER] },
  { id: 211, name: '셀리카', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.YELESS_LEGENDS], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 212, name: '이미르', factions: [Faction.LEGION_OF_GLORY, Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS], classes: [HeroClass.DEMON, HeroClass.HOLY] },
  { id: 213, name: '비리아', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.YELESS_LEGENDS], classes: [HeroClass.MAGE] },
  { id: 214, name: '세라피나', factions: [Faction.EMPIRE_HONOR, Faction.STRATEGIC_MASTERS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.ASSASSIN] },
  { id: 215, name: '빛의소환사', factions: [Faction.LEGION_OF_GLORY, Faction.PRINCESS_ALLIANCE, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 216, name: '시온', factions: [Faction.PROTAGONIST, Faction.LEGION_OF_GLORY, Faction.YELESS_LEGENDS], classes: [HeroClass.CAVALRY, HeroClass.INFANTRY] },
  { id: 217, name: '티아나', factions: [Faction.LEGION_OF_GLORY, Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS], classes: [HeroClass.ASSASSIN, HeroClass.LANCER] },
  { id: 218, name: '캡틴코만도&후버', factions: [Faction.PROTAGONIST, Faction.STRATEGIC_MASTERS, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 219, name: '맥&긴주', factions: [Faction.PROTAGONIST, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.ASSASSIN] },
  { id: 220, name: '엔야', factions: [Faction.ORIGINS_OF_LIGHT, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 221, name: '아리아', factions: [Faction.LEGION_OF_GLORY, Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.HOLY] },
  { id: 222, name: '이리아', factions: [Faction.LEGION_OF_GLORY, Faction.ORIGINS_OF_LIGHT, Faction.PRINCESS_ALLIANCE], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 223, name: '노노린', factions: [Faction.LEGION_OF_GLORY, Faction.STRATEGIC_MASTERS, Faction.METEOR_STRIKE], classes: [HeroClass.INFANTRY, HeroClass.AQUATIC] },
  { id: 224, name: '사프린', factions: [Faction.ORIGINS_OF_LIGHT, Faction.TRANSCENDENCE, Faction.RE_INCARNATION_TENSEI], classes: [HeroClass.MAGE, HeroClass.HOLY] },
  { id: 225, name: '염룡파멸자', factions: [Faction.EMPIRE_HONOR, Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS], classes: [HeroClass.DEMON, HeroClass.FLYER] },
  { id: 226, name: '란델', factions: [Faction.DARK_REINCARNATION, Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 227, name: '날개꺾인새', factions: [Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE, Faction.TRANSCENDENCE], classes: [HeroClass.ARCHER, HeroClass.ASSASSIN] },
  { id: 228, name: '마리로즈', factions: [Faction.PRINCESS_ALLIANCE, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.INFANTRY] },
  { id: 229, name: '뇨텐구', factions: [Faction.PRINCESS_ALLIANCE, Faction.TRANSCENDENCE, Faction.TIME_AND_SPACE], classes: [HeroClass.FLYER] },
  { id: 230, name: '카스미', factions: [Faction.PROTAGONIST, Faction.METEOR_STRIKE, Faction.TIME_AND_SPACE], classes: [HeroClass.ASSASSIN] },
  { id: 231, name: '시엘나', factions: [Faction.ORIGINS_OF_LIGHT, Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS], classes: [HeroClass.DEMON, HeroClass.MAGE] },
  { id: 232, name: '샘', factions: [Faction.ORIGINS_OF_LIGHT, Faction.METEOR_STRIKE, Faction.YELESS_LEGENDS], classes: [HeroClass.DEMON, HeroClass.INFANTRY] },
  { id: 233, name: '마카엘라', factions: [Faction.PRINCESS_ALLIANCE, Faction.METEOR_STRIKE, Faction.ORIGINS_OF_LIGHT], classes: [HeroClass.HOLY, HeroClass.ASSASSIN] },
  { id: 234, name: '마안의서큐버스', factions: [Faction.DARK_REINCARNATION, Faction.METEOR_STRIKE, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.ASSASSIN] },
  { id: 235, name: '루크만', factions: [Faction.LEGION_OF_GLORY, Faction.STRATEGIC_MASTERS, Faction.YELESS_LEGENDS], classes: [HeroClass.INFANTRY, HeroClass.LANCER] },
  { id: 236, name: '아브샤이트', factions: [Faction.DARK_REINCARNATION, Faction.YELESS_LEGENDS, Faction.TRANSCENDENCE], classes: [HeroClass.DEMON, HeroClass.INFANTRY] },
];

export const PUZZLE_DEFINITIONS: PuzzleDefinition[] = [
  {
    type: PuzzleType.CITY_HALL,
    totalSlots: 10,
    nodes: [
      { id: 'T1', label: 'T1', row: 'top', requiredClass: HeroClass.MAGE },
      { id: 'T2', label: 'T2', row: 'top', requiredClass: HeroClass.MAGE },
      { id: 'T3', label: 'T3', row: 'top', requiredClass: HeroClass.MAGE },
      { id: 'M1', label: 'M1', row: 'mid', requiredClass: HeroClass.HOLY },
      { id: 'M2', label: 'M2', row: 'mid', requiredClass: HeroClass.HOLY },
      { id: 'M3', label: 'M3', row: 'mid', requiredClass: HeroClass.HOLY },
      { id: 'B1', label: 'B1', row: 'bot', requiredClass: HeroClass.FLYER },
      { id: 'B2', label: 'B2', row: 'bot', requiredClass: HeroClass.FLYER },
      { id: 'B3', label: 'B3', row: 'bot', requiredClass: HeroClass.FLYER },
      { id: 'B4', label: 'B4', row: 'bot', requiredClass: HeroClass.FLYER },
    ],
    edges: [
      ['T1', 'T2'], ['T2', 'T3'], ['M1', 'M2'], ['M2', 'M3'], ['B1', 'B2'], ['B2', 'B3'], ['B3', 'B4'],
      ['T1', 'M1'], ['T2', 'M1'], ['T2', 'M2'], ['T2', 'M3'], ['T3', 'M3'],
      ['M1', 'B1'], ['M1', 'B2'], ['M2', 'B2'], ['M2', 'B3'], ['M3', 'B3'], ['M3', 'B4']
    ]
  },
  {
    type: PuzzleType.FOREST_LEAGUE,
    totalSlots: 6,
    nodes: [
      { id: 'T1', label: 'T1', row: 'top', requiredClass: HeroClass.HOLY },
      { id: 'T2', label: 'T2', row: 'top', requiredClass: HeroClass.HOLY },
      { id: 'T3', label: 'T3', row: 'top', requiredClass: HeroClass.HOLY },
      { id: 'M1', label: 'M1', row: 'mid', requiredClass: HeroClass.MAGE },
      { id: 'M2', label: 'M2', row: 'mid', requiredClass: HeroClass.MAGE },
      { id: 'B1', label: 'B1', row: 'bot', requiredClass: HeroClass.CAVALRY }
    ],
    edges: [
      ['T1', 'T2'], ['T2', 'T3'], ['M1', 'M2'],
      ['T1', 'M1'], ['T2', 'M1'], ['T2', 'M2'], ['T3', 'M2'],
      ['M1', 'B1'], ['M2', 'B1']
    ]
  },
  {
    type: PuzzleType.EARTH_INSTITUTE,
    totalSlots: 6,
    nodes: [
      { id: 'T1', label: 'T1', row: 'top', requiredClass: HeroClass.CAVALRY },
      { id: 'T2', label: 'T2', row: 'top', requiredClass: HeroClass.CAVALRY },
      { id: 'M1', label: 'M1', row: 'mid', requiredClass: HeroClass.ARCHER },
      { id: 'M2', label: 'M2', row: 'mid', requiredClass: HeroClass.ARCHER },
      { id: 'B1', label: 'B1', row: 'bot', requiredClass: HeroClass.LANCER },
      { id: 'B2', label: 'B2', row: 'bot', requiredClass: HeroClass.LANCER }
    ],
    edges: [
      ['T1', 'T2'], ['M1', 'M2'], ['B1', 'B2'],
      ['T1', 'M1'], ['T2', 'M2'],
      ['M1', 'B1'], ['M2', 'B2'],
      ['T1', 'B1'], ['T2', 'B2']
    ]
  },
  {
    type: PuzzleType.IRON_BROTHERHOOD,
    totalSlots: 6,
    nodes: [
      { id: 'T1', label: 'T1', row: 'top', requiredClass: HeroClass.FLYER },
      { id: 'M1', label: 'M1', row: 'mid', requiredClass: HeroClass.INFANTRY },
      { id: 'M2', label: 'M2', row: 'mid', requiredClass: HeroClass.INFANTRY },
      { id: 'B1', label: 'B1', row: 'bot', requiredClass: HeroClass.DEMON },
      { id: 'B2', label: 'B2', row: 'bot', requiredClass: HeroClass.DEMON },
      { id: 'B3', label: 'B3', row: 'bot', requiredClass: HeroClass.DEMON }
    ],
    edges: [
      ['M1', 'M2'], ['B1', 'B2'], ['B2', 'B3'],
      ['T1', 'M1'], ['T1', 'M2'],
      ['M1', 'B1'], ['M1', 'B2'], ['M2', 'B2'], ['M2', 'B3']
    ]
  }
];
